export const OTP_PURPOSES = {
  LOGIN: 'LOGIN_OTP',
  PAYMENT_COLLECTION: 'PAYMENT_COLLECTION_OTP',
  DELIVERY: 'DELIVERY_OTP',
};

export const ORDER_STATUSES = [
  'NEW',
  'ACCEPTED',
  'HOLD',
  'PROCESSING',
  'READY_TO_DISPATCH',
  'PARTIALLY_DISPATCHED',
  'FULLY_DISPATCHED',
  'OUT_FOR_DELIVERY',
  'PARTIALLY_DELIVERED',
  'DELIVERED',
  'CANCELLED',
];

export const COLLECTION_STATUSES = [
  'COLLECTED',
  'HANDOVER_PENDING',
  'ACCOUNT_VERIFICATION',
  'ACCOUNT_VERIFIED',
  'VERIFICATION_FAILED',
];

export const staffProfile = {
  id: 'STF-0042',
  name: 'Arjun Sharma',
  mobile: '9876543210',
  email: 'arjun@ezyenquiry.in',
  designation: 'Senior Sales Executive',
  department: 'Sales & Customer Success',
  company: 'EzyEnquiry Business Solutions',
  employeeCode: 'EZY-STF-042',
  status: 'ACTIVE',
  permissions: [
    'Customer Management',
    'Create Quotations',
    'View Assigned Orders',
    'Record Collections',
    'Handover Collections',
  ],
};

export const productsSeed = [
  {
    id: 'PRD-001',
    code: 'TILE-001',
    name: 'Marble White',
    brand: 'EzyCeram',
    category: 'Floor Tile',
    subCategory: 'Glazed Vitrified',
    tileType: 'GVT',
    grade: 'Premium',
    color: 'White',
    hsnCode: '69072100',
    size: '600 × 600 mm',
    finish: 'Gloss',
    unit: 'Boxes',
    stock: 500,
    rate: 830,
    mrp: 1150,
    retailPrice: 980,
    dealerPrice: 830,
    purchasePrice: 720,
    pcsPerBox: 4,
    sqftPerBox: 15.5,
    gst: 18,
    wholesaler: 'Bharat Ceramics',
    location: 'Bengaluru',
  },
  {
    id: 'PRD-002',
    code: 'TILE-118',
    name: 'Onyx Beige',
    brand: 'StoneCraft',
    category: 'Wall Tile',
    subCategory: 'Ceramic Wall',
    tileType: 'Ceramic',
    grade: 'Standard',
    color: 'Beige',
    hsnCode: '69072300',
    size: '300 × 600 mm',
    finish: 'Matt',
    unit: 'Boxes',
    stock: 184,
    rate: 690,
    mrp: 940,
    retailPrice: 800,
    dealerPrice: 690,
    purchasePrice: 585,
    pcsPerBox: 6,
    sqftPerBox: 11.6,
    gst: 18,
    wholesaler: 'Metro Tile Depot',
    location: 'Jaipur',
  },
  {
    id: 'PRD-003',
    code: 'TILE-204',
    name: 'Graphite Slate',
    brand: 'UrbanStone',
    category: 'Parking Tile',
    subCategory: 'Heavy Duty',
    tileType: 'Vitrified',
    grade: 'Commercial',
    color: 'Graphite',
    hsnCode: '69072200',
    size: '400 × 400 mm',
    finish: 'Rustic',
    unit: 'Boxes',
    stock: 72,
    rate: 540,
    mrp: 760,
    retailPrice: 640,
    dealerPrice: 540,
    purchasePrice: 455,
    pcsPerBox: 8,
    sqftPerBox: 13.8,
    gst: 18,
    wholesaler: 'Shakti Distributors',
    location: 'Delhi',
  },
  {
    id: 'PRD-004',
    code: 'TILE-311',
    name: 'Calacatta Gold',
    brand: 'EzyCeram',
    category: 'Floor Tile',
    subCategory: 'Glazed Vitrified',
    tileType: 'GVT',
    grade: 'Premium',
    color: 'Gold',
    hsnCode: '69072100',
    size: '600 × 1200 mm',
    finish: 'High Gloss',
    unit: 'Boxes',
    stock: 96,
    rate: 850,
    mrp: 1280,
    retailPrice: 1020,
    dealerPrice: 850,
    purchasePrice: 730,
    pcsPerBox: 2,
    sqftPerBox: 15.5,
    gst: 18,
    wholesaler: 'Bharat Ceramics',
    location: 'Bengaluru',
  },
];

export const customersSeed = [
  {
    id: 'CUS-1001',
    name: 'Shree Balaji Tiles',
    mobile: '9810012456',
    email: 'accounts@balajitiles.in',
    gst: '08AALCS4182P1Z7',
    address: '22, Vaishali Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302021',
    type: 'Retailer',
    outstanding: 48560,
    orderCount: 8,
    lastOrder: '18 Aug 2026',
  },
  {
    id: 'CUS-1002',
    name: 'Modern Home Studio',
    mobile: '9845098742',
    email: 'hello@modernhome.in',
    gst: '29AAFCM7821K1Z9',
    address: '14, Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    type: 'Customer',
    outstanding: 18654,
    orderCount: 4,
    lastOrder: '24 Aug 2026',
  },
  {
    id: 'CUS-1003',
    name: 'Royal Buildmart',
    mobile: '9898123412',
    email: 'purchase@royalbuildmart.in',
    gst: '24AAECR6620H1ZA',
    address: 'S.G. Highway',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380054',
    type: 'Retailer',
    outstanding: 0,
    orderCount: 12,
    lastOrder: '21 Aug 2026',
  },
];

export const quotationsSeed = [
  {
    id: 'QT-00125',
    createdByType: 'RETAILER',
    createdByName: 'Shree Balaji Tiles',
    creationAction: 'SEND_ENQUIRY',
    customerId: 'CUS-1001',
    customerName: 'Shree Balaji Tiles',
    productId: 'PRD-001',
    productName: 'Marble White',
    quantity: 20,
    unit: 'Boxes',
    rate: 830,
    discount: 400,
    gst: 18,
    deliveryCharge: 500,
    total: 19616,
    wholesaler: 'Bharat Ceramics',
    expectedDelivery: '30 Aug 2026',
    status: 'NEGOTIATION',
    createdAt: '24 Aug 2026',
    remarks: 'Retailer requested ₹820. Wholesaler offered ₹830 final.',
  },
  {
    id: 'QT-00124',
    createdByType: 'STAFF',
    createdByName: 'Arjun Sharma',
    creationAction: 'STAFF_QUOTATION',
    adminVisibility: 'SUBMITTED_TO_ADMIN',
    customerId: 'CUS-1002',
    customerName: 'Modern Home Studio',
    productId: 'PRD-002',
    productName: 'Onyx Beige',
    quantity: 14,
    unit: 'Boxes',
    rate: 690,
    discount: 200,
    gst: 18,
    deliveryCharge: 450,
    total: 11613,
    wholesaler: 'Metro Tile Depot',
    expectedDelivery: '28 Aug 2026',
    status: 'ACCEPTED',
    createdAt: '22 Aug 2026',
    remarks: 'Created by Staff for a direct customer requirement.',
  },
  {
    id: 'QT-00123',
    createdByType: 'RETAILER',
    createdByName: 'Royal Buildmart',
    creationAction: 'SEND_ENQUIRY',
    customerId: 'CUS-1003',
    customerName: 'Royal Buildmart',
    productId: 'PRD-003',
    productName: 'Graphite Slate',
    quantity: 32,
    unit: 'Boxes',
    rate: 540,
    discount: 0,
    gst: 18,
    deliveryCharge: 900,
    total: 21290,
    wholesaler: 'Shakti Distributors',
    expectedDelivery: '02 Sep 2026',
    status: 'RESPONDED',
    createdAt: '21 Aug 2026',
    remarks: 'Wholesaler responded; retailer decision is pending.',
  },
  {
    id: 'QT-00122',
    createdByType: 'STAFF',
    createdByName: 'Arjun Sharma',
    creationAction: 'STAFF_QUOTATION',
    adminVisibility: 'SUBMITTED_TO_ADMIN',
    customerId: 'CUS-1002',
    customerName: 'Modern Home Studio',
    productId: 'PRD-004',
    productName: 'Calacatta Gold',
    quantity: 18,
    unit: 'Boxes',
    rate: 850,
    discount: 0,
    gst: 18,
    deliveryCharge: 600,
    total: 18654,
    wholesaler: 'Bharat Ceramics',
    expectedDelivery: '27 Aug 2026',
    status: 'ACCEPTED',
    createdAt: '20 Aug 2026',
    remarks: 'Staff-created quotation accepted by the customer.',
  },
  {
    id: 'QT-00126',
    createdByType: 'STAFF',
    createdByName: 'Arjun Sharma',
    creationAction: 'STAFF_QUOTATION',
    adminVisibility: 'SUBMITTED_TO_ADMIN',
    customerId: 'CUS-1001',
    customerName: 'Shree Balaji Tiles',
    productId: 'PRD-002',
    productName: 'Onyx Beige',
    quantity: 24,
    unit: 'Boxes',
    rate: 690,
    discount: 0,
    gst: 18,
    deliveryCharge: 600,
    total: 20141,
    wholesaler: 'Metro Tile Depot',
    expectedDelivery: 'Within 7 days',
    status: 'PENDING',
    createdAt: '27 Aug 2026',
    remarks: 'Submitted to Admin for review.',
  },
];

export const dispatchesSeed = [
  {
    id: 'DSP-0081',
    orderId: 'SO-00125',
    quantity: 10,
    status: 'DELIVERED',
    driverName: 'Ramesh Kumar',
    driverMobile: '9988776655',
    vehicleNumber: 'KA 01 AB 4582',
    lrNumber: 'LR-88342',
    transport: 'FastTrack Logistics',
    dispatchDate: '23 Aug 2026',
    expectedDelivery: '24 Aug 2026',
    expectedDeliveryTime: '04:00 PM',
    deliveredDate: '24 Aug 2026',
    deliveryOtpPurpose: 'DELIVERY_OTP',
    deliveryOtpStatus: 'OTP_VERIFIED',
  },
  {
    id: 'DSP-0083',
    orderId: 'SO-00128',
    quantity: 24,
    status: 'READY_TO_DISPATCH',
    driverName: 'To be assigned',
    driverMobile: '—',
    vehicleNumber: '—',
    lrNumber: '—',
    transport: 'Metro Transport',
    dispatchDate: '—',
    expectedDelivery: '30 Aug 2026',
    expectedDeliveryTime: '—',
    deliveredDate: '—',
    deliveryOtpPurpose: 'DELIVERY_OTP',
    deliveryOtpStatus: 'PENDING',
  },
  {
    id: 'DSP-0078',
    orderId: 'SO-00127',
    quantity: 32,
    status: 'DELIVERED',
    driverName: 'Vijay Singh',
    driverMobile: '9877112233',
    vehicleNumber: 'GJ 01 KT 2214',
    lrNumber: 'LR-87991',
    transport: 'Shree Cargo',
    dispatchDate: '20 Aug 2026',
    expectedDelivery: '21 Aug 2026',
    expectedDeliveryTime: '01:00 PM',
    deliveredDate: '21 Aug 2026',
    deliveryOtpPurpose: 'DELIVERY_OTP',
    deliveryOtpStatus: 'OTP_VERIFIED',
  },
  {
    id: 'DSP-0074',
    orderId: 'SO-00129',
    quantity: 18,
    status: 'OUT_FOR_DELIVERY',
    driverName: 'Manoj Yadav',
    driverMobile: '9877001122',
    vehicleNumber: 'KA 05 MT 9081',
    lrNumber: 'LR-87115',
    transport: 'CityLink Cargo',
    dispatchDate: '25 Aug 2026',
    expectedDelivery: '27 Aug 2026',
    expectedDeliveryTime: '06:00 PM',
    deliveredDate: '—',
    deliveryOtpPurpose: 'DELIVERY_OTP',
    deliveryOtpStatus: 'PENDING',
  },
];

export const ordersSeed = [
  {
    id: 'SO-00125',
    quotationId: 'QT-00125',
    customerId: 'CUS-1001',
    customerName: 'Shree Balaji Tiles',
    wholesaler: 'Bharat Ceramics',
    productName: 'Marble White',
    productCode: 'TILE-001',
    quantity: 20,
    unit: 'Boxes',
    rate: 830,
    total: 19616,
    picked: 10,
    dispatched: 10,
    delivered: 10,
    status: 'PARTIALLY_DELIVERED',
    expectedDelivery: '30 Aug 2026',
    deliveryAddress: '22, Vaishali Nagar, Jaipur, Rajasthan',
    dispatchIds: ['DSP-0081'],
    invoiceIds: ['INV-00125'],
    holdReason: null,
    holdRemarks: null,
    heldBy: null,
    heldAt: null,
  },
  {
    id: 'SO-00126',
    quotationId: 'QT-00124',
    customerId: 'CUS-1002',
    customerName: 'Modern Home Studio',
    wholesaler: 'Metro Tile Depot',
    productName: 'Onyx Beige',
    productCode: 'TILE-118',
    quantity: 14,
    unit: 'Boxes',
    rate: 690,
    total: 11613,
    picked: 0,
    dispatched: 0,
    delivered: 0,
    status: 'HOLD',
    previousStatus: 'CONFIRMED',
    expectedDelivery: 'To be revised',
    deliveryAddress: '14, Indiranagar, Bengaluru, Karnataka',
    dispatchIds: [],
    invoiceIds: [],
    holdReason: 'PRICE_APPROVAL',
    holdRemarks: 'Waiting for Admin approval on revised customer discount.',
    heldBy: 'Metro Tile Depot',
    heldAt: '26 Aug 2026, 03:20 PM',
  },
  {
    id: 'SO-00127',
    quotationId: 'QT-00123',
    customerId: 'CUS-1003',
    customerName: 'Royal Buildmart',
    wholesaler: 'Shakti Distributors',
    productName: 'Graphite Slate',
    productCode: 'TILE-204',
    quantity: 32,
    unit: 'Boxes',
    rate: 540,
    total: 21290,
    picked: 32,
    dispatched: 32,
    delivered: 32,
    status: 'DELIVERED',
    expectedDelivery: '21 Aug 2026',
    deliveryAddress: 'S.G. Highway, Ahmedabad, Gujarat',
    dispatchIds: ['DSP-0078'],
    invoiceIds: ['INV-00124'],
    holdReason: null,
    holdRemarks: null,
    heldBy: null,
    heldAt: null,
  },
  {
    id: 'SO-00128',
    quotationId: 'QT-00126',
    customerId: 'CUS-1001',
    customerName: 'Shree Balaji Tiles',
    wholesaler: 'Metro Tile Depot',
    productName: 'Onyx Beige',
    productCode: 'TILE-118',
    quantity: 24,
    unit: 'Boxes',
    rate: 690,
    total: 20141,
    picked: 24,
    dispatched: 0,
    delivered: 0,
    status: 'READY_TO_DISPATCH',
    expectedDelivery: '30 Aug 2026',
    deliveryAddress: '22, Vaishali Nagar, Jaipur, Rajasthan',
    dispatchIds: ['DSP-0083'],
    invoiceIds: [],
    holdReason: null,
    holdRemarks: null,
    heldBy: null,
    heldAt: null,
  },
  {
    id: 'SO-00129',
    quotationId: 'QT-00122',
    customerId: 'CUS-1002',
    customerName: 'Modern Home Studio',
    wholesaler: 'Bharat Ceramics',
    productName: 'Calacatta Gold',
    productCode: 'TILE-311',
    quantity: 18,
    unit: 'Boxes',
    rate: 850,
    total: 18654,
    picked: 18,
    dispatched: 18,
    delivered: 0,
    status: 'OUT_FOR_DELIVERY',
    expectedDelivery: '27 Aug 2026',
    deliveryAddress: '14, Indiranagar, Bengaluru, Karnataka',
    dispatchIds: ['DSP-0074'],
    invoiceIds: ['INV-00122'],
    holdReason: null,
    holdRemarks: null,
    heldBy: null,
    heldAt: null,
  },
];

export const invoicesSeed = [
  {
    id: 'INV-00125',
    orderId: 'SO-00125',
    dispatchId: 'DSP-0081',
    customerId: 'CUS-1001',
    customerName: 'Shree Balaji Tiles',
    productName: 'Marble White',
    quantity: 10,
    unit: 'Boxes',
    subtotal: 8300,
    gstAmount: 1494,
    deliveryCharge: 500,
    total: 10294,
    paidAmount: 5000,
    balance: 5294,
    dueDate: '31 Aug 2026',
    status: 'PARTIALLY_PAID',
  },
  {
    id: 'INV-00124',
    orderId: 'SO-00127',
    dispatchId: 'DSP-0078',
    customerId: 'CUS-1003',
    customerName: 'Royal Buildmart',
    productName: 'Graphite Slate',
    quantity: 32,
    unit: 'Boxes',
    subtotal: 17280,
    gstAmount: 3110,
    deliveryCharge: 900,
    total: 21290,
    paidAmount: 21290,
    balance: 0,
    dueDate: '28 Aug 2026',
    status: 'PAID',
  },
  {
    id: 'INV-00122',
    orderId: 'SO-00129',
    dispatchId: 'DSP-0074',
    customerId: 'CUS-1002',
    customerName: 'Modern Home Studio',
    productName: 'Calacatta Gold',
    quantity: 18,
    unit: 'Boxes',
    subtotal: 15300,
    gstAmount: 2754,
    deliveryCharge: 600,
    total: 18654,
    paidAmount: 0,
    balance: 18654,
    dueDate: '26 Aug 2026',
    status: 'PENDING',
  },
];

export const paymentsSeed = [
  {
    id: 'PAY-0058',
    invoiceId: 'INV-00124',
    orderId: 'SO-00127',
    customerId: 'CUS-1003',
    customerName: 'Royal Buildmart',
    amount: 21290,
    mode: 'UPI',
    reference: 'UPI825391104',
    status: 'VERIFIED',
    date: '22 Aug 2026',
    createdBy: 'Retailer',
  },
  {
    id: 'PAY-0059',
    invoiceId: 'INV-00125',
    orderId: 'SO-00125',
    customerId: 'CUS-1001',
    customerName: 'Shree Balaji Tiles',
    amount: 5000,
    mode: 'CASH',
    reference: 'CASH-REC-118',
    status: 'COLLECTED',
    date: '27 Aug 2026',
    createdBy: 'Arjun Sharma',
  },
];

export const collectionsSeed = [
  {
    id: 'COL-00101',
    paymentId: 'PAY-0059',
    invoiceId: 'INV-00125',
    orderId: 'SO-00125',
    customerId: 'CUS-1001',
    customerName: 'Shree Balaji Tiles',
    staffId: 'STF-0042',
    staffName: 'Arjun Sharma',
    amount: 5000,
    mode: 'CASH',
    reference: 'CASH-REC-118',
    collectedAt: '27 Aug 2026, 10:15 AM',
    handedOverAt: null,
    verifiedAt: null,
    status: 'COLLECTED',
  },
  {
    id: 'COL-00100',
    paymentId: 'PAY-0058',
    invoiceId: 'INV-00124',
    orderId: 'SO-00127',
    customerId: 'CUS-1003',
    customerName: 'Royal Buildmart',
    staffId: null,
    staffName: 'Retailer direct payment',
    amount: 21290,
    mode: 'UPI',
    reference: 'UPI825391104',
    collectedAt: '22 Aug 2026, 02:10 PM',
    handedOverAt: 'Not applicable',
    verifiedAt: '22 Aug 2026, 02:11 PM',
    status: 'ACCOUNT_VERIFIED',
  },
];

export const notificationsSeed = [
  {
    id: 'NOT-101',
    type: 'quotation',
    title: 'Quotation negotiation updated',
    message: 'Bharat Ceramics offered ₹830 final for QT-00125.',
    time: '10 min ago',
    read: false,
    route: 'QuotationDetail',
    entityId: 'QT-00125',
  },
  {
    id: 'NOT-102',
    type: 'order',
    title: 'Order placed on HOLD',
    message: 'SO-00126 is waiting for price approval.',
    time: '45 min ago',
    read: false,
    route: 'OrderDetail',
    entityId: 'SO-00126',
  },
  {
    id: 'NOT-103',
    type: 'collection',
    title: 'Collection awaiting handover',
    message: 'COL-00101 for ₹5,000 must be handed over to Accounts.',
    time: '1 hr ago',
    read: false,
    route: 'CollectionDetail',
    entityId: 'COL-00101',
  },
  {
    id: 'NOT-104',
    type: 'delivery',
    title: 'Partial delivery completed',
    message: 'Delivery OTP verified for DSP-0081. 10 of 20 boxes delivered.',
    time: 'Yesterday',
    read: true,
    route: 'DispatchDetail',
    entityId: 'DSP-0081',
  },
];
